// Code generated by protoc-gen-go. DO NOT EDIT.
// source: customerdef.proto

package customer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CustomerRequest struct {
	Id                   int32                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string                     `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string                     `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Addresses            []*CustomerRequest_Address `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CustomerRequest) Reset()         { *m = CustomerRequest{} }
func (m *CustomerRequest) String() string { return proto.CompactTextString(m) }
func (*CustomerRequest) ProtoMessage()    {}
func (*CustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c982099d756a16b, []int{0}
}
func (m *CustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerRequest.Unmarshal(m, b)
}
func (m *CustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerRequest.Marshal(b, m, deterministic)
}
func (dst *CustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerRequest.Merge(dst, src)
}
func (m *CustomerRequest) XXX_Size() int {
	return xxx_messageInfo_CustomerRequest.Size(m)
}
func (m *CustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerRequest proto.InternalMessageInfo

func (m *CustomerRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CustomerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustomerRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CustomerRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CustomerRequest) GetAddresses() []*CustomerRequest_Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type CustomerRequest_Address struct {
	Street               string   `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Zip                  string   `protobuf:"bytes,4,opt,name=zip,proto3" json:"zip,omitempty"`
	IsShippingAddress    bool     `protobuf:"varint,5,opt,name=isShippingAddress,proto3" json:"isShippingAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerRequest_Address) Reset()         { *m = CustomerRequest_Address{} }
func (m *CustomerRequest_Address) String() string { return proto.CompactTextString(m) }
func (*CustomerRequest_Address) ProtoMessage()    {}
func (*CustomerRequest_Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c982099d756a16b, []int{0, 0}
}
func (m *CustomerRequest_Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerRequest_Address.Unmarshal(m, b)
}
func (m *CustomerRequest_Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerRequest_Address.Marshal(b, m, deterministic)
}
func (dst *CustomerRequest_Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerRequest_Address.Merge(dst, src)
}
func (m *CustomerRequest_Address) XXX_Size() int {
	return xxx_messageInfo_CustomerRequest_Address.Size(m)
}
func (m *CustomerRequest_Address) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerRequest_Address.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerRequest_Address proto.InternalMessageInfo

func (m *CustomerRequest_Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *CustomerRequest_Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *CustomerRequest_Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *CustomerRequest_Address) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *CustomerRequest_Address) GetIsShippingAddress() bool {
	if m != nil {
		return m.IsShippingAddress
	}
	return false
}

type CustomerResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerResponse) Reset()         { *m = CustomerResponse{} }
func (m *CustomerResponse) String() string { return proto.CompactTextString(m) }
func (*CustomerResponse) ProtoMessage()    {}
func (*CustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c982099d756a16b, []int{1}
}
func (m *CustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerResponse.Unmarshal(m, b)
}
func (m *CustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerResponse.Marshal(b, m, deterministic)
}
func (dst *CustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerResponse.Merge(dst, src)
}
func (m *CustomerResponse) XXX_Size() int {
	return xxx_messageInfo_CustomerResponse.Size(m)
}
func (m *CustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerResponse proto.InternalMessageInfo

func (m *CustomerResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CustomerResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CustomerFilter struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerFilter) Reset()         { *m = CustomerFilter{} }
func (m *CustomerFilter) String() string { return proto.CompactTextString(m) }
func (*CustomerFilter) ProtoMessage()    {}
func (*CustomerFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c982099d756a16b, []int{2}
}
func (m *CustomerFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerFilter.Unmarshal(m, b)
}
func (m *CustomerFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerFilter.Marshal(b, m, deterministic)
}
func (dst *CustomerFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerFilter.Merge(dst, src)
}
func (m *CustomerFilter) XXX_Size() int {
	return xxx_messageInfo_CustomerFilter.Size(m)
}
func (m *CustomerFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerFilter.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerFilter proto.InternalMessageInfo

func (m *CustomerFilter) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func init() {
	proto.RegisterType((*CustomerRequest)(nil), "customer.CustomerRequest")
	proto.RegisterType((*CustomerRequest_Address)(nil), "customer.CustomerRequest.Address")
	proto.RegisterType((*CustomerResponse)(nil), "customer.CustomerResponse")
	proto.RegisterType((*CustomerFilter)(nil), "customer.CustomerFilter")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerClient is the client API for Customer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerClient interface {
	// Get all customer with filter - A serer-to-client steaming RPC
	GetCustomers(ctx context.Context, in *CustomerFilter, opts ...grpc.CallOption) (Customer_GetCustomersClient, error)
	// Create a new Customer - A Simple RCP
	CreateCustomer(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (Customer_CreateCustomerClient, error)
}

type customerClient struct {
	cc *grpc.ClientConn
}

func NewCustomerClient(cc *grpc.ClientConn) CustomerClient {
	return &customerClient{cc}
}

func (c *customerClient) GetCustomers(ctx context.Context, in *CustomerFilter, opts ...grpc.CallOption) (Customer_GetCustomersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Customer_serviceDesc.Streams[0], "/customer.Customer/GetCustomers", opts...)
	if err != nil {
		return nil, err
	}
	x := &customerGetCustomersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Customer_GetCustomersClient interface {
	Recv() (*CustomerRequest, error)
	grpc.ClientStream
}

type customerGetCustomersClient struct {
	grpc.ClientStream
}

func (x *customerGetCustomersClient) Recv() (*CustomerRequest, error) {
	m := new(CustomerRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *customerClient) CreateCustomer(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (Customer_CreateCustomerClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Customer_serviceDesc.Streams[1], "/customer.Customer/CreateCustomer", opts...)
	if err != nil {
		return nil, err
	}
	x := &customerCreateCustomerClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Customer_CreateCustomerClient interface {
	Recv() (*CustomerResponse, error)
	grpc.ClientStream
}

type customerCreateCustomerClient struct {
	grpc.ClientStream
}

func (x *customerCreateCustomerClient) Recv() (*CustomerResponse, error) {
	m := new(CustomerResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CustomerServer is the server API for Customer service.
type CustomerServer interface {
	// Get all customer with filter - A serer-to-client steaming RPC
	GetCustomers(*CustomerFilter, Customer_GetCustomersServer) error
	// Create a new Customer - A Simple RCP
	CreateCustomer(*CustomerRequest, Customer_CreateCustomerServer) error
}

func RegisterCustomerServer(s *grpc.Server, srv CustomerServer) {
	s.RegisterService(&_Customer_serviceDesc, srv)
}

func _Customer_GetCustomers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CustomerFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CustomerServer).GetCustomers(m, &customerGetCustomersServer{stream})
}

type Customer_GetCustomersServer interface {
	Send(*CustomerRequest) error
	grpc.ServerStream
}

type customerGetCustomersServer struct {
	grpc.ServerStream
}

func (x *customerGetCustomersServer) Send(m *CustomerRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _Customer_CreateCustomer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CustomerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CustomerServer).CreateCustomer(m, &customerCreateCustomerServer{stream})
}

type Customer_CreateCustomerServer interface {
	Send(*CustomerResponse) error
	grpc.ServerStream
}

type customerCreateCustomerServer struct {
	grpc.ServerStream
}

func (x *customerCreateCustomerServer) Send(m *CustomerResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Customer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "customer.Customer",
	HandlerType: (*CustomerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCustomers",
			Handler:       _Customer_GetCustomers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CreateCustomer",
			Handler:       _Customer_CreateCustomer_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "customerdef.proto",
}

func init() { proto.RegisterFile("customerdef.proto", fileDescriptor_8c982099d756a16b) }

var fileDescriptor_8c982099d756a16b = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0x71, 0xda, 0xf4, 0x67, 0x40, 0xa5, 0xb5, 0x10, 0x32, 0x59, 0x85, 0xac, 0x22, 0x84,
	0x22, 0x54, 0xb6, 0x48, 0x08, 0x55, 0xa2, 0x0b, 0x76, 0xe1, 0x04, 0x21, 0x19, 0xa8, 0x45, 0x9b,
	0x04, 0x8f, 0x2b, 0x54, 0xae, 0xc0, 0x25, 0x38, 0x02, 0x47, 0x44, 0x76, 0x62, 0x2a, 0x51, 0xba,
	0x9b, 0xf7, 0x3c, 0xf3, 0xfc, 0x79, 0x64, 0x98, 0xe4, 0x6b, 0xd2, 0xd5, 0x0a, 0x55, 0x81, 0xcf,
	0x49, 0xad, 0x2a, 0x5d, 0xf1, 0x81, 0xb3, 0xa2, 0x6f, 0x0f, 0x8e, 0x67, 0xad, 0x48, 0xf1, 0x6d,
	0x8d, 0xa4, 0xf9, 0x08, 0x3c, 0x59, 0x08, 0x16, 0xb2, 0xd8, 0x4f, 0x3d, 0x59, 0x70, 0x0e, 0xdd,
	0x32, 0x5b, 0xa1, 0xf0, 0x42, 0x16, 0x0f, 0x53, 0x5b, 0xf3, 0x13, 0xf0, 0x71, 0x95, 0xc9, 0xa5,
	0xe8, 0x58, 0xb3, 0x11, 0xc6, 0xad, 0x17, 0x55, 0x89, 0xa2, 0xdb, 0xb8, 0x56, 0xf0, 0x5b, 0x18,
	0x66, 0x45, 0xa1, 0x90, 0x08, 0x49, 0xf8, 0x61, 0x27, 0x3e, 0x9c, 0x9e, 0x27, 0x8e, 0x20, 0xf9,
	0x73, 0x7b, 0x72, 0xd7, 0xb4, 0xa6, 0xdb, 0x99, 0xe0, 0x93, 0x41, 0xbf, 0xb5, 0xf9, 0x29, 0xf4,
	0x48, 0x2b, 0x44, 0x6d, 0x01, 0x87, 0x69, 0xab, 0x0c, 0x64, 0x2e, 0xf5, 0xc6, 0x41, 0x9a, 0xda,
	0xe0, 0x90, 0xce, 0x34, 0x3a, 0x48, 0x2b, 0xf8, 0x18, 0x3a, 0x1f, 0xb2, 0x6e, 0x11, 0x4d, 0xc9,
	0x2f, 0x61, 0x22, 0xe9, 0x71, 0x21, 0xeb, 0x5a, 0x96, 0x2f, 0xed, 0x45, 0xc2, 0x0f, 0x59, 0x3c,
	0x48, 0x77, 0x0f, 0xa2, 0x1b, 0x18, 0x6f, 0x99, 0xa9, 0xae, 0x4a, 0xc2, 0x9d, 0x95, 0x09, 0xe8,
	0xd3, 0x3a, 0xcf, 0x4d, 0x8e, 0x67, 0x73, 0x9c, 0x8c, 0x2e, 0x60, 0xe4, 0xa6, 0xef, 0xe5, 0x52,
	0xa3, 0x32, 0xbd, 0xaf, 0xb8, 0x79, 0xaf, 0x54, 0xd1, 0x3e, 0xc9, 0xc9, 0xe9, 0x17, 0x83, 0x81,
	0x6b, 0xe6, 0x73, 0x38, 0x9a, 0xa3, 0x76, 0x92, 0xb8, 0xd8, 0x5d, 0x61, 0x13, 0x18, 0x9c, 0xed,
	0x5d, 0x6e, 0x74, 0x70, 0xc5, 0xf8, 0x03, 0x8c, 0x66, 0x0a, 0x33, 0x8d, 0xbf, 0xd1, 0xfb, 0x07,
	0x82, 0xe0, 0xbf, 0xa3, 0xe6, 0xd1, 0x26, 0xec, 0xa9, 0x67, 0x3f, 0xd4, 0xf5, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xce, 0xe9, 0x57, 0x64, 0x65, 0x02, 0x00, 0x00,
}
